# user-dp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-wordpress
  labels:
    app: user-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-wordpress
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1      
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: user-wordpress
        tier: frontend
    spec:
      containers:
        - image: 535597585675.dkr.ecr.ap-northeast-2.amazonaws.com/product_ci:13.0
          securityContext:
          runAsUser: 0
          name: user-wordpress
          ports:
            - containerPort: 80
              name: user-wordpress
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      env:
        - name: DB_NAME
          value: "wordpress"
        - name: DB_USER
          value: "sstc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secrets
              key: db_password
        - name: DB_HOST
          value: "gg05-rds.clvnjtk7wlyl.ap-northeast-2.rds.amazonaws.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-wordpress
  labels:
    app: admin-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-wordpress
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1      
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: admin-wordpress
        tier: frontend
    spec:
      containers:
      - name: admin-wordpress
        image: 535597585675.dkr.ecr.ap-northeast-2.amazonaws.com/product_ci:13.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
          name: admin-wordpress
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: DB_NAME
          value: "wordpress"
        - name: DB_USER
          value: "sstc"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secrets
              key: db_password
        - name: DB_HOST
          value: "gg05-rds.clvnjtk7wlyl.ap-northeast-2.rds.amazonaws.com"
