# user-dp.yamlfrontend
apiVersion: argoproj.io/v1alpha1
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: rollout-bluegreen
  labels:
    app: rollout-bluegreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-bluegreen
      tier: frontend
  template:
    metadata:
      labels:
        app: rollout-bluegreen
        tier: frontend
    spec:
      containers:
      - name: rollout-bluegreen
        image: 535597585675.dkr.ecr.ap-northeast-2.amazonaws.com/product_ci:6.0
        #image: 535597585675.dkr.ecr.ap-northeast-2.amazonaws.com/product_ci:7.0
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secrets
              key: DB_PASSWORD
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
          name: user-wordpress
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: rollout-bluegreen-active
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: rollout-bluegreen-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false

---
  
# user-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort

---

# user-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort

---

# wordpress-ingresss.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rollout-bluegreen-active
              port:
                number: 80
